gains:
  torso_lift_joint: {p: 30000,  d: 250, i: 0.1, i_clamp: 1.5}
  head_1_joint: {p: 100,  d: 0, i: 10, i_clamp: 1.5}
  head_2_joint: {p: 100,  d: 0, i: 10, i_clamp: 1.5}
  
  gripper_left_finger_joint: {p: 100,  d: 0, i: 10, i_clamp: 1.5}
  gripper_right_finger_joint: {p: 100,  d: 0, i: 10, i_clamp: 1.5} 

  arm_left_1_joint: &arm_1_pid {p: 3000, d: 0.6, i: 0, i_clamp: 3, torque_clamp: 60}
  arm_left_2_joint: &arm_2_pid {p: 3000, d: 5, i: 0, i_clamp: 3, torque_clamp: 50}
  arm_left_3_joint: &arm_3_pid {p: 100, d: 1, i: 0, i_clamp: 3, torque_clamp: 50}
  arm_left_4_joint: &arm_4_pid {p: 500, d: 5, i: 0, i_clamp: 3, torque_clamp: 50}
  arm_left_5_joint: &arm_5_pid {p: 200, d: 0, i: 0, i_clamp: 3, torque_clamp: 50}
  arm_left_6_joint: &arm_6_pid {p: 50, d: 0.3, i: 0, i_clamp: 3, torque_clamp: 50}
  arm_left_7_joint: &arm_7_pid {p: 10, d: 0, i: 0, i_clamp: 3, torque_clamp: 50}

  arm_right_1_joint: *arm_1_pid
  arm_right_2_joint: *arm_2_pid
  arm_right_3_joint: *arm_3_pid
  arm_right_4_joint: *arm_4_pid
  arm_right_5_joint: *arm_5_pid
  arm_right_6_joint: *arm_6_pid
  arm_right_7_joint: *arm_7_pid

