<?xml version="1.0"?>
<package format="2">
  <name>tiago_pro_gazebo</name>
  <version>0.0.2</version>
  <description>The tiago_pro_gazebo package</description>

  <maintainer email="narcis.miguel@pal-robotics.com">Narcis Miguel</maintainer>

  <license>Propietary</license>

  <buildtool_depend>catkin</buildtool_depend>
  
  <exec_depend>gazebo_plugins</exec_depend>
  <exec_depend>pal_gazebo_plugins</exec_depend>
  <exec_depend>pal_gazebo_worlds</exec_depend>
  <exec_depend>pal_hardware_gazebo</exec_depend>
  <exec_depend>tiago_pro_description</exec_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>play_motion_msgs</exec_depend>

</package>
