<?xml version="1.0"?>
<package format="2">
  <name>tiago_pro_simulation</name>
  <version>0.0.2</version>
  <description>The tiago_pro_simulation package</description>

  <maintainer email="narcis.miguel@pal-robotics.com">Narcis Miguel</maintainer>

  <license>Propietary</license>

  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>tiago_pro_gazebo</exec_depend>

  <export>
    <metapackage/>
  </export>
</package>
